# Default values for hello-nginx
replicaCount: 1

image:
  repository: registry.kube-system.svc.cluster.local:80/hostaway/hello-nginx
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

# Ingress configuration (disabled by default)
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: hello-nginx.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}
tolerations: []
affinity: {}
